### PR TITLE
Introduce Provisioning Architecture Diagram

### PR DESCRIPTION
**Pull request by yogeshbdeshpande**

### CODE REVIEW

**Comment by thomas-fossati** [comment]
I am not sure I understand this PR: Is this supposed to be merged without accompanying text or being referenced from existing documentation?

**Comment by yogeshbdeshpande** [comment]
> I am not sure I understand this PR: Is this supposed to be merged without accompanying text or being referenced from existing documentation?

This is just a place holder so that we do not lose this. Yes eventually this will be embedded in a suitable text to be referred!

**Comment by thomas-fossati** [comment]
> > I am not sure I understand this PR: Is this supposed to be merged without accompanying text or being referenced from existing documentation?
> 
> This is just a place holder so that we do not lose this. Yes eventually this will be embedded in a suitable text to be referred!

OK, let's track that future activity in a task though, otherwise in a couple of weeks this ends up being a mystery object :-)

**Comment by yogeshbdeshpande** [comment]
> > > I am not sure I understand this PR: Is this supposed to be merged without accompanying text or being referenced from existing documentation?
> > 
> > 
> > This is just a place holder so that we do not lose this. Yes eventually this will be embedded in a suitable text to be referred!
> 
> OK, let's track that future activity in a task though, otherwise in a couple of weeks this ends up being a mystery object :-)

Agree, tracked it via : https://github.com/veraison/veraison/issues/71

**Review by thomas-fossati — COMMENTED** [review]
As discussed, let's have only one (editable PNG), not both.  Otherwise we can run into consistency troubles.

**Comment by yogeshbdeshpande** [comment]
> As discussed, let's have only one (editable PNG), not both. Otherwise we can run into consistency troubles.

Agree, let me introduce this!

**Review by thomas-fossati — APPROVED** [review]
fantastic, thanks!

**Pull request merged**
